config:
  webhook: &webhook-config
    check_every: 24h
    webhook_token: KC8SFDCTLu
#   slack: &slack-config
#     username: 'concourse'
#     channel: '#web-team-deploy'
#     icon_url: 'http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png'
#   failure: &slack-failure
#     put: slack-alert
#     params:
#       <<: *slack-config
#       text: |
#         Stylguide build failed:
#         https://concourse.common-services.telia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
      tag: latest

  - name: node_modules-cache-resource-type
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: "8"

  - name: s3-resource
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple

resources:
  - name: styleguide-pr
    type: pull-request
    check_every: 24h
    webhook_token: MQxZf6F6Tz
    source: &styleguide-pr-source
      repository: TeliaSoneraNorge/styleguide
      ignore_paths: [ ci ]
      access_token: ((teliasoneranorge-access-token))

  - name: styleguide
    type: git
    source: &styleguide-source
      uri: git@github.com:TeliaSoneraNorge/styleguide.git
      branch: feature/concourse-pipeline
      private_key: ((channel-api-functions-deploy-key))

  - name: node-tasks
    type: git
    source:
        uri: git@github.com:mhd999/go-tasks.git
        branch: master
        private_key: ((channel-api-functions-deploy-key))

  - name: website
    type: s3-resource
    source:
      bucket: styleguide.channelapi-at.telia.no
      access_key_id: ((telia-no-channelapi-stage-access-key))
      secret_access_key: ((telia-no-channelapi-stage-secret-key))
      region: "eu-west-1"
      options:
      - "--exclude '*'"
      - "--include 'styleguide/dist/*'"

#   - name: website
#     type: s3
#     source:
#       bucket: styleguide.channelapi-at.telia.no
#       access_key_id: ((telia-no-channelapi-stage-access-key))
#       secret_access_key: ((telia-no-channelapi-stage-secret-key))
#       session_token: ((telia-no-channelapi-stage-session-token))
#       private: true
#       region_name: "eu-west-1"

#   - name: slack-alert
#     type: slack-notification
#     source:
#       url: https://hooks.slack.com/services/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

  - name: node_modules
    type: node_modules-cache-resource-type
    source:
      <<: *styleguide-source
      paths:
        - package.json

groups:
  - name: Master
    jobs:
    - lint
    - build-and-upload
    - upload

  - name: PR
    jobs:
    - lint-pr

jobs:
  - name: lint
    serial: true
    serial_groups: [lint-job]
    public: true
    plan:
    - aggregate:
      - get: node_modules
        passed:
      - get: styleguide
        trigger: true
        version: every
        passed:
      - get: node-tasks
        params:
          submodules:
          - node

    - task: run-lint
      file: node-tasks/node/8.10.0.yml
      input_mapping:
        source: styleguide
        dependencies: node_modules
      params:
        command: lint
        directory: /
     # on_failure: *slack-failure

  - name: lint-pr
    serial: true
    public: true
    plan:
    - aggregate:
      - get: node_modules
        passed:
      - get: styleguide-pr
        trigger: true
        version: every
        passed:
      - get: node-tasks
        params:
          submodules:
          - node

    - task: run-lint
      file: node-tasks/node/8.10.0.yml
      input_mapping:
        source: styleguide-pr
        dependencies: node_modules
      params:
        command: lint
        directory: /
     # on_failure: *slack-failure


  - name: build-and-upload
    serial: true
    serial_groups: [lint-job, build-and-upload-job]
    plan:
    - aggregate:
      - get: styleguide
        passed: [ lint ]
      - get: node_modules
        passed: [ lint ]

    - task: build-and-upload-styleguide
      file: styleguide/ci/tasks/build.yml

  - name: upload
    serial: true
    serial_groups: [lint-job, build-and-upload-job, upload-job]
    plan:
    - aggregate:
      - get: styleguide
        passed: [ lint, build-and-upload ]
      - get: node_modules
        passed: [ lint, build-and-upload ]
    - put: website



    #   on_failure:
    #     put: slack-alert
    #     params:
    #         <<: *slack-config
    #         text: 'Styleguide build failed (component-lib):
    #         https://concourse.common-services.telia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    #         '
    # - task: build-website
    #   file: node-tasks/node/8.10.0.yml
    #   input_mapping:
    #     dependencies: node_modules
    #   params:
    #     entrypoint:
    #     command: build
    #     directory: /
    # #   on_failure:
    #     put: slack-alert
    #     params:
    #         <<: *slack-config
    #         text: 'Styleguide build failed:

    #         https://concourse.common-services.telia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    #         '